config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here

  resources :contest, only: [:show] do
    resources :participations, only: [:create, :new]
  end
  get "/concours", to: "contest#show"
  get 'participation/:id/subscribe', :to => 'participation#subscribe', :as => :subscribe


  namespace :admin do

    get "/contests/:id/select_winner" => 'contests#select_winner', as: :select_winner

    resources :contests do
      resources :participation
    end
  end


end

app/models/spree/contest.rb
module Spree
  class Contest < Spree::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: [:slugged, :finders]
    has_many :participations, :dependent => :destroy
    belongs_to :selected_winner, class_name: 'Participation'
    before_save :generate_slug


    def subscription_number
      participations.count
    end
    def opt_in_number
      participations.where(subscribed: :true).count
    end
    def opt_in_rate
      ((opt_in_number.to_f/subscription_number.to_f)*100).round(2)
    end

    def slug_candidates
      [:name]
    end

    def generate_slug
      self.slug = name.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '') unless self.slug.present?
    end
    def select_winner
      opted_in_vote_count = self.participations.where(subscribed: :true).count*2

      not_opted_in_vote_count = self.participations.where(subscribed: :false).count
      selected = rand(0..(opted_in_vote_count + not_opted_in_vote_count))
      if selected < opted_in_vote_count
        self.selected_winner = self.participations.where(subscribed: :true).limit(1).offset((selected/2).floor).first
      else
        self.selected_winner = self.participations.where(subscribed: :false).limit(1).offset(selected - opted_in_vote_count).first
      end
      self.save
      puts "/*********************************/"
      puts "SELECTING WINER"

      puts "opted_in vote : "+opted_in_vote_count.to_s
      puts "not opted_in vote : "+not_opted_in_vote_count.to_s
      puts "random picked : "+selected.to_s
      puts selected_winner.inspect
      puts "/*********************************/"

    end

    def self.active_contest
       contest = Spree::Contest.where("date_begin < NOW()").where("date_end >= NOW()").order(:date_begin).last()
    end

    def to_csv
      CSV.generate do |csv|
        csv << Spree::Participation.column_names
        participations.each do |part|
          csv << part.attributes.values_at(*Spree::Participation.column_names)
        end
      end
    end

  end
end

app/models/spree/participation.rb
module Spree
  class Participation < Spree::Base
    require 'mailchimp'
    belongs_to :contest
    validates_uniqueness_of :email, :scope => :contest_id
    before_save :add_to_mailchimp

    before_validation :upcase_zip
    canadian_postal_code = /\A[ABCEGHJKLMNPRSTVXY]{1}\d{1}[A-Z]{1} *\d{1}[A-Z]{1}\d{1}$\z/
    validates :zip, format: { with: canadian_postal_code }

    def add_to_mailchimp
      begin
        if self.subscribed && self.contest.mailchimp_api_key && self.contest.mailchimp_list_id
          mailchimp =       Mailchimp::API.new(self.contest.mailchimp_api_key)
          mailchimp.lists.subscribe(self.contest.mailchimp_list_id, { "email" => self.email})
        end
      rescue Mailchimp::ValidationError => e
        errors.add(:email, "invalide")
        false
      rescue Mailchimp::Error => e
        errors.add(:email, "invalide")
        false
      rescue Mailchimp::ListAlreadySubscribedError => e
        true
      end
    end

    def upcase_zip
      self.zip = self.zip.upcase if self.zip.present?
    end

  end
end

app/controllers/spree/admin/contests_controller.rb
module Spree
  module Admin
    class ContestsController < ResourceController

      def index
        @contests = Spree::Contest.all
      end

      def select_winner
        @contest = Spree::Contest.includes(:participations).find(params[:id])
        @contest.select_winner
        redirect_to admin_contest_path(@contest)
      end
      def show
        @contest = Spree::Contest.find(params[:id])
        respond_to do |format|
          format.html
          format.csv { send_data @contest.to_csv }
        end
      end

    end
  end
end

app/controllers/spree/admin/participation_controller.rb
module Spree
  module Admin
    class ParticipationController < ResourceController

      def index
        @contest = Spree::Contest.includes(:participations).find(params[:id])
        @participations = @contest.participations
      end

      def destroy
        @participation = Spree::Participation.find(params[:id])
        @contest = @participation.contest
        @participation.destroy
        redirect_to admin_contest_path(@contest)
      end

    end
  end
end

app/controllers/spree/contest_controller.rb
module Spree
  class ContestController < Spree::StoreController

    respond_to :js, :html
    def show
      if params[:id]
       @contest = Spree::Contest.find(params[:id])
      else
        @contest = Spree::Contest.order(:date_end).last
      end

      unless @contest.date_begin < Date.today && @contest.date_end >=Date.today
        redirect_to(root_path) and return
      end

      @participation = Spree::Participation.new()
    end

    private
    def permitted_params
      [:participation => [:id, :name, :postal_code, :email]]
    end

  end
end

app/controllers/spree/participations_controller.rb
module Spree
  class ParticipationsController < Spree::StoreController

    respond_to :js, :html
    def subscribe
      @participation = Spree::Participation.find(params[:id])
      @participation.subscribed = true
    end

    def create
      @contest = Spree::Contest.find(params[:contest_id])
      unless params[:terms]
        flash[:notice] = "Vous n'avez pas accepté les termes"
        redirect_to(:back) and return

      end

      @participation = Spree::Participation.new(participation_params)
      @participation.subscribed = !(params[:subscribed].blank?)
      @participation.contest = @contest


      unless verify_recaptcha(model: @participation)
        flash[:notice] = "Vous devez remplir le recaptcha."
        redirect_to(:back) and return
      end

      unless @participation.save
        flash[:notice] = "Le formulaire a été mal rempli ou le email est déjà entré."
        redirect_to(:back) and return
      end

      respond_to do |format|
        format.html {}
        format.js {render :layout => false}
      end

    end




    def participation_params
      params.require(:participation).permit(:name, :email, :zip, :subscribed, :contest_id)
    end


  end
end

app/views/spree/admin/contests/_form.html.erb
<div data-hook="admin_inside_store_locations_form">

  <div class="row">

    <div class="col-md-4" data-hook="admin_product_form_left">
      <%= f.field_container :name, class: ['form-group'] do %>
          <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
          <%= error_message_on :name, :name %>
          <%= text_field :contest, :name, :class => 'form-control' %>
      <% end %>
    </div>
    <div class="col-md-4" data-hook="admin_product_form_left">
      <%= f.field_container :mailchimp_api_key, class: ['form-group'] do %>
          <%= f.label :mailchimp_api_key, Spree.t(:mailchimp_api_key) %> <span class="required">*</span><br />
          <%= error_message_on :mailchimp_api_key, :mailchimp_api_key %>
          <%= text_field :contest, :mailchimp_api_key, :class => 'form-control' %>
      <% end %>
    </div>
    <div class="col-md-4" data-hook="admin_product_form_left">
      <%= f.field_container :mailchimp_list_id, class: ['form-group'] do %>
          <%= f.label :mailchimp_list_id, Spree.t(:mailchimp_list_id) %> <span class="required">*</span><br />
          <%= error_message_on :mailchimp_list_id, :mailchimp_list_id %>
          <%= text_field :contest, :mailchimp_list_id, :class => 'form-control' %>
      <% end %>
    </div>

    </div>

  <div class="row">


    <div class="col-md-4" data-hook="admin_product_form_left">
      <%= f.field_container :slug, class: ['form-group'] do %>
          <%= f.label :slug, Spree.t(:slug) %><br />
          <%= error_message_on :slug, :slug %>
          <%= text_field :contest, :slug, :class => 'form-control' %>
      <% end %>
    </div>

    <div class="col-md-4" data-hook="admin_product_form_left">
      <%= f.field_container "Page des termes et conditions", class: ['form-group'] do %>
          <%= f.label :terms_link, Spree.t(:terms_link) %> <span class="required">*</span><br />
          <%= error_message_on :terms_link, :terms_link %>
          <%= text_field :contest, :terms_link, :class => 'form-control' %>
      <% end %>
    </div>

  </div>
  <div id="date_begin" class="form-group">
    <%= f.label :date_begin %>
    <%= f.text_field :date_begin, :value => datepicker_field_value(@contest.date_begin), :class => 'datepicker datepicker-from form-control' %>
  </div>

  <div id="date_end" class="form-group">
    <%= f.label :date_end %>
    <%= f.text_field :date_end, :value => datepicker_field_value(@contest.date_end), :class => 'datepicker datepicker-to form-control' %>
  </div>

  </div>
</div>

app/views/spree/admin/contests/edit.html.erb
<%= render 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
    <%= @contest.name %>
<% end %>

<% content_for :page_actions do %>
    <li>
      <%= button_link_to Spree.t(:back_to_store_concours), spree.admin_contests_path, :icon => 'arrow-left' %>
    </li>
<% end %>

<%= form_for [:admin, @contest] do |f| %>

    <%= render :partial => 'form', :locals => { :f => f } %>

    <fieldset class="no-border-top">
      <br>
      <div class="filter-actions actions" data-hook="buttons">
        <%= button Spree.t(:create), 'ok' %>
      </div>
    </fieldset>

<% end %>

app/views/spree/admin/contests/index.html.erb
<%= button_link_to Spree.t(:new_contest), new_admin_contest_path, { :class => "btn-success", :icon => 'add', :id => 'admin_new_contest' } %>

<% if @contests.any? %>
    <table class="table" id='listing_stock_locations' data-hook>
      <thead>
      <tr data-hook="stock_locations_header">
        <th><%= Spree.t(:date_begin) %></th>
        <th><%= t(:date_end) %></th>
        <th><%= Spree.t(:name) %></th>
        <th class="actions"></th>
      </tr>
      </thead>
      <tbody>
      <% @contests.each do |contest| %>
          <tr>
            <td><%= contest.date_begin %></td>
            <td><%= contest.date_end %></td>
            <td><%= link_to contest.name, admin_contest_path(contest)%> </td>
            <td class="actions actions-2 text-right">
              <%= link_to_edit(contest.id, class: 'admin_edit_option_type', no_text: true) %>
              <%= link_to_delete(contest, no_text: true) %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found) %>
    </div>
<% end %>

app/views/spree/admin/contests/new.html.erb
<%= render 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
    <%= "Nouveau concours" %>
<% end %>

<% content_for :page_actions do %>
    <li>
      <%= button_link_to Spree.t(:back_to_store_concours), spree.admin_contests_path, :icon => 'arrow-left' %>
    </li>
<% end %>

<%= form_for [:admin, @contest] do |f| %>

    <%= render :partial => 'form', :locals => { :f => f } %>

    <fieldset class="no-border-top">
      <br>
      <br>

      <div class="filter-actions actions" data-hook="buttons">
        <%= button Spree.t(:create), 'ok' %>
      </div>
    </fieldset>

<% end %>

app/views/spree/admin/contests/show.html.erb
<%= button_link_to Spree.t(:edit_contest), edit_admin_contest_path(@contest), { :class => "btn-success", :icon => 'add', :id => 'admin_edit_contest' } %>
<%= button_link_to Spree.t(:select_winner), admin_select_winner_path(@contest), { :class => "btn-success", :icon => 'add' } %>
<%= button_link_to Spree.t(:csv ), admin_contest_path(@contest, format: "csv"), { :class => "btn-success", :icon => 'add', :id => 'admin_edit_contest' } %>


<% if @contest.selected_winner %>
    <div class ="alert alert-info" >
        <div class="row">
          <div class="col-md-8" data-hook="admin_product_form_left">
            <%= Spree.t(:selected_winner) %> :
          </div>
        </div>
        <div class="row">
          <div class="col-md-4" data-hook="admin_product_form_left">
            <%= label :name, Spree.t(:name) %> :
            <%= @contest.selected_winner.name %>
          </div>

          <div class="col-md-4" data-hook="admin_product_form_left">
            <%= label :email, Spree.t(:email) %> :
            <%= @contest.selected_winner.email %>
          </div>

        </div>
    </div>
<% end %>

<br/>

<div class ="alert alert-info" >
  <div class="row">
    <div class="col-md-8" data-hook="admin_product_form_left">
      <%= Spree.t(:contest_info) %> :
    </div>
  </div>
  <div class="row">
    <div class="col-md-4" data-hook="admin_product_form_left">
      <%= label :subscription_no, Spree.t(:subscription_no) %> :
      <%= @contest.subscription_number %>
    </div>
    <div class="col-md-4" data-hook="admin_product_form_left">
      <%= label :opt_in_no, Spree.t(:opt_in_no) %> :
      <%= @contest.opt_in_number %>
    </div>

    <div class="col-md-4" data-hook="admin_product_form_left">
      <%= label :opt_in_rate, Spree.t(:opt_in_rate) %> :
      <%= @contest.opt_in_rate %> %
    </div>

  </div>
</div>


<% if (@participations = @contest.participations.page(params[:page])).any? %>
    <table class="table" id='listing_stock_movements'>
      <colgroup>
        <col style="width: 35%">
        <col style="width: 20%">
        <col style="width: 45%">
      </colgroup>
      <thead>
      <tr data-hook="admin_stock_movements_index_headers">
        <th><%= Spree.t(:nom) %>
        <th><%= Spree.t(:email) %></th>
        <th><%= Spree.t(:zip) %></th>
        <th><%= Spree.t(:infolettre) %></th>

      </tr>
      </thead>
      <tbody>
      <% @participations.each do |participation|%>
          <tr id="<%= spree_dom_id participation %>" data-hook="admin_participation_index_rows">
            <td><%= participation.name %></td>
            <td><%= participation.email %></td>
            <td><%= participation.zip %></td>
            <td><%= participation.subscribed ? "oui" : "non" %></td>

          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Participation)) %>
    </div>
<% end %>

<%= paginate @participations %>

app/views/spree/admin/shared/sub_menu/_contest.html.erb
<ul class="nav nav-sidebar">
  <%= tab *Spree::BackendConfiguration::USER_TABS, url: spree.admin_contests_path, icon: 'user' %>
</ul>

app/views/spree/contest/show.html.erb
<div class="content">
  <div class="container">


      <h3><%= @contest.name %></h3>
      <div id="notice">
      </div>

      <div class="description">
        <%= render :partial => 'spree/shared/participation_form', :locals =>{contest: @contest} %>
      </div>
    <div style="display:none" id="subscribe">
    </div>
  </div>
</div>

app/views/spree/contest/show.js.erb
$("#notice").html("<%= flash[:notice] %>")

app/views/spree/participations/_form.html.erb
<div class="container">
  <div class="content_box">

    <section class="section">

      <div class="content_section">

        <%= render 'shared/error_messages', active_object: @participation %>

        <%= form_for @participation do |f| %>

            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control'%>
            </div>

            <div class="form-group">
              <%= f.label :email %>
              <%= f.text_field :email, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :zip %>
              <%= f.text_field :zip, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :terms %>
              <%= f.checkbox_field :terms, class: 'form-control' %>
            </div>

            <div class="actions">
              <%= f.submit %>
            </div>

        <% end %>
      </div>
    </section>
  </div>
</div>

app/views/spree/participations/create.js.erb
$(".contest").html("<%=j render :partial => 'spree/shared/participation_confirm', :locals => { :participation => @participation } %>");



$("#share").click(function(e){
    var urlpost = "<%= contest_url(@participation.contest) %>";
    e.preventDefault();
    FB.ui({
        method: 'share',
        href: urlpost
    }, function(response){

    });
});

app/views/spree/participations/new.html.erb
<%= render partial: 'form' %>

app/views/spree/shared/_participation_confirm.html.erb
<div style="display: block;" class="step_3">

  <div class="xlightgreen">

    <h3>Merci d'avoir participé!</h3>
    <span>Vous avez <%= participation.subscribed ? "2" : "1" %> chance<%= participation.subscribed ? "s" : "" %> de gagner</span>
    <div class="footer-socials">
      <ul class="socials-menu clear">
        <li><a href="https://www.facebook.com/modechoc" class="facebook" target="_blank"><i class="fa fa-facebook"></i></a></li>
        <li><a href="https://www.pinterest.com/modechoc/" class="pinterest" target="_blank"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="http://instagram.com/modechoc" class="instagram" target="_blank"><i class="fa fa-instagram"></i></a></li>
      </ul>
    </div>

    <span id="share" data-href="<%= contest_url(participation.contest) %>" class="link">Partager</span>

    <a title="Continuer à magasiner" href="<%= root_path %>" class="link red">Continuer sur <strong>modechoc.ca</strong></a>

  </div>

  <a title="Consulter le blogue" href="http://blogue.modechoc.ca" target="_blank" class="link">Consulter le <strong>blogue</strong></a>


</div>

app/views/spree/shared/_participation_form.html.erb
<div class ="contest">
  <%= form_for [contest, @participation], method: "post", remote: true do |f| %>

    <div class="step_1 step">
      <div class="notice"></div>

      <h4>Courez la chance de gagner</h4>
      <h3>Un voyage pour 4</h3>
      <p class="text">Au splash memories de Punta Cana en république Dominicaine<br />| Une valeur de 6000 $ |</p>

      <h5>Inscription</h5>

      <div class="clear">

        <div class="field-row clear">

          <div class="field-holder">

            <%= f.label :name, "Nom et Prénom*"%>
            <%= f.text_field :name, class: 'name'%>

          </div>

          <div class="field-holder last">

            <%= f.label :email , "Courriel*" %>
            <%= f.text_field :email, class: 'form-control' %>


          </div>

        </div>


        <div class="field-row clear">

          <div class="field-holder">
            <%= f.label :zip, "Code postal*" %>
            <%= f.text_field :zip, class: 'form-control' %>
          </div>

          <div class="field-holder last">
            <label>&nbsp;</label>
            <div class="clear">

              <div class="checkboxholder">
                <input type="checkbox" name="terms" id="terms" value="1">
                <label id="chk_newsletter" class="custom-checkbox" for="terms">
                  <span></span>
                </label>
              </div>

              <p class="left">J'ai lu et j'accepte les <%= link_to "règlements du concours", @contest.terms_link, target: "_blank" %><br />Fin du concours 1<sup>er</sup> avril 2016.</p>
            </div>
          </div>

        </div>

        <div class="field-row clear">

          <div class="field-holder">
            <%= image_tag 'logo-michel-barette.png' %>
          </div>

          <div class="field-holder last">
            <input type="submit" value="Étape suivante" class="next_step"/>
          </div>

        </div>

      </div><!-- .clear -->

    </div>

    <div style="display: none;" class="step_2 step">
      <div class="notice"></div>

      <% if @contest.mailchimp_api_key && @contest.mailchimp_list_id %>

      <h3>Obtenez des<br />chances supplémentaires<br />de gagner!</h3>

      <div class="clear">

        <div class="field-row clear">

          <div class="field-holder info darkgreen full">
            <div class="footer-socials clear">
              <ul class="socials-menu">
                <li><a href="#" class="facebook" target="_blank"><i class="fa fa-envelope"></i></a></li>
              </ul>
              <h3>Obtenez une chance supplémentaire de gagner en vous inscrivant à l'infolettre</h3>

              <p>Soyez le premier informé<br />de l'identité du gagnant!</p>
          </div>

        </div>

        <div class="field-row clear">

          <div class="field-holder full">
            <%= f.submit "Participez" %>
          </div>

        </div>

      </div>
      <% end %>


    </div>
    </div>

<% end %>
</div>

app/views/spree/shared/_subscribe.html.erb
<div class="container">
  <div class="content_box">

    <section class="section">

      <div class="content_section">
        <%= button_link_to "s'incrire a l'infolettre pour un vote de plus", subscribe_path(participation.id) %>

      </div>
    </section>
  </div>
</div>